/*
 * SVAR - config.h
 * This file was automatically generated by CMake.
 */

/* Define to 1 if debugging is enabled. */
/* #undef DEBUG */

/* Define to 1 if PortAudio is enabled. */
/* #undef ENABLE_PORTAUDIO */

/* Define to 1 if Mp3Lame is enabled. */
/* #undef ENABLE_MP3LAME */

/* Define to 1 if SNDFile is enabled. */
/* #undef ENABLE_SNDFILE */

/* Define to 1 if Ogg Vorbis is enabled. */
/* #undef ENABLE_VORBIS */

/* Define to the name of this project. */
#define PROJECT_NAME "svar"

/* Define to the version of this project. */
#define PROJECT_VERSION "1.2.0"
